module.exports = {
    SERVER_REQUEST_ERR: `Prázdna požiadavka`,
    SERVER_VALIDATION_ERR: `Údaje boli nesprávne vyplnené`,
    SERVER_PAGE_NOT_FOUND: `Je nám ľúto, ale požadovaná stránka nebola nájdená`,
    DATABASE_STRUCTURE: `Štruktúra databázy bola úspešne vytvorená`,
    DATABASE_STRUCTURE_ERR: `Nepodarilo sa vytvoriť štruktúru databázy`,
    DATABASE_SEED: `Databáza bola úspešne naplnená údajmi`,
    DATABASE_SEED_ERR: `Databázu sa nepodarilo naplniť údajmi`,

    CREATE_REGION_ERR: `Vytvorenie kraja sa nepodarilo, skúste znova`,
    UPDATE_REGION_ERR: `Aktualizácia kraja sa nepodarilo, skúste znova`,
    DELETE_REGION_ERR: `Odstránenie kraja sa nepodarilo, skúste znova`,
    GET_REGION_ERR: `Ľutujeme ale kraj s identifikačním číslom neexistuje`,
    REGION_NOT_FOUND: `Ľutujeme ale nenašiel sa žiadný kraj`,

    CREATE_DISTRICT_ERR: `Vytvorenie okresu sa nepodarilo, skúste znova`,
    UPDATE_DISTRICT_ERR: `Aktualizácia okresu sa nepodarilo, skúste znova`,
    DELETE_DISTRICT_ERR: `Odstránenie okresu sa nepodarilo, skúste znova`,
    GET_DISTRICT_ERR: `Ľutujeme ale okres s identifikačním číslom neexistuje`,
    DISTRICT_NOT_FOUND: `Ľutujeme ale nenašiel sa žiadný okres`,

    CREATE_VILLAGE_ERR: `Vytvorenie mesta/obce sa nepodarilo, skúste znova`,
    UPDATE_VILLAGE_ERR: `Aktualizácia mesta/obce sa nepodarilo, skúste znova`,
    DELETE_VILLAGE_ERR: `Odstránenie mesta/obce sa nepodarilo, skúste znova`,
    GET_VILLAGE_ERR: `Ľutujeme ale mesto/obec s identifikačním číslom neexistuje`,
    VILLAGE_NOT_FOUND: `Ľutujeme ale nenašlo sa žiadne mesto/obec`,

    REGION_NAME_LENGHT: `Minimálna dlžka kraja je 3 a maximalná je 64`,
    REGION_NAME_ALPHA: `Nesprávný formát názov kraja`,
    REGION_SHORTCUT_LENGHT: `Nesprávna dlžka iniciály kraja, dlžka musí byť 2`,
    REGION_SHORTCUT_ALPHA: `Nesprávný formát iniciály kraja`,
    REGION_USE_INT: `Hodnota musí byť 1 alebo 0`,
    REGION_ID_INT: `Nesprávný formát identifikacného čísla`,
    REGION_PAGE_NUMBER_INT: `Nesprávný formát číslo strany`,
    REGION_PAGE_SIZE_INT: `Nesprávný formát veľkosť strany`,

    DISTRICT_NAME_LENGHT: `Minimálna dlžka okresu je 3 a maximalná je 64`,
    DISTRICT_NAME_ALPHA: `Nesprávný formát názov okresu`,
    DISTRICT_VEH_REG_NUM_LENGHT: `Nesprávna dlžka iniciály okresu, dlžka musí byť 2`,
    DISTRICT_VEH_REG_NUM_ALPHA: `Nesprávný formát iniciály okresu`,
    DISTRICT_CODE_INT: `Nesprávný formát kód okresu`,
    DISTRICT_REGION_ID_INT: `Nesprávný formát identifikacného čísla kraja`,
    DISTRICT_USE_INT: `Hodnota musí byť 1 alebo 0`,
    DISTRICT_ID_INT: `Nesprávný formát identifikacného čísla`,
    DISTRICT_PAGE_NUMBER_INT: `Nesprávný formát číslo strany`,
    DISTRICT_PAGE_SIZE_INT: `Nesprávný formát veľkosť strany`,

    VILLAGE_FULL_NAME_LENGHT: `Minimálna dlžka obce/mesta je 3 a maximalná je 64`,
    VILLAGE_FULL_NAME_ALPHA: `Nesprávný formát názov obce/mesta`,
    VILLAGE_SHORT_NAME_LENGHT: `Minimálna dlžka obce/mesta je 3 a maximalná je 32, (kratký názov)`,
    VILLAGE_SHORT_NAME_ALPHA: `Nesprávný formát názov obce/mesta, (kratký názov)`,
    VILLAGE_ZIP_ALPHA_NUMERIC: `Nesprávný formát PSČ`,
    VILLAGE_DISTRICT_ID_INT: `Nesprávný formát identifikacného čísla kraja`,
    VILLAGE_REGION_ID_INT: `Nesprávný formát identifikacného čísla kraja`,
    VILLAGE_USE_INT: `Hodnota musí byť 1 alebo 0`,
    VILLAGE_ID_INT: `Nesprávný formát identifikacného čísla`,
    VILLAGE_PAGE_NUMBER_INT: `Nesprávný formát číslo strany`,
    VILLAGE_PAGE_SIZE_INT: `Nesprávný formát veľkosť strany`
};